### PR TITLE
Vignettes

### PR DESCRIPTION
**Pull request by tomaszaba**
Hi Ernest, 

In this PR I addressed issues #14 , #15 , #16. 
I have also addressed the issue about the use of the verb to wrangle on age. 

I look forward to your feedback.

Thanks.

### CODE REVIEW

**Review by ernestguevarra — COMMENTED** [review]
@tomaszaba I've looked at your vignettes. Two major comments here:

* [x] the front matter for the YAML component of the `.qmd` files need to be updated

This is so that they will be rendered specifically as vignettes particularly in the build setup and in the CRAN setup.

* [ ] vignettes directory should only contain the vignette documents.

In your commit, you added the directories created when building the vignette. These will be flagged by CRAN as unrecognised directories/files.

Instead of reviewing this, I will add to this PR to make it work for CRAN (if possible) and to make it work with pkgdown (which we know already have limitations).

I think if we really want to write all these things that you want to include in a vignette, let's make the vignette standard (meaning Rmd) and then you just write a book using Quarto where you can write as long as you want all the guides to using the package.

**Comment by ernestguevarra** [comment]
@tomaszaba I've pushed in infrastructural changes to your PR that does the following:

1. Update the YAML front matter of your qmd vignettes;
2. setup `_pkgdown.yml` to style pkgdown website so we can view the vignettes online; this uses nutriverse template
3. setup pkgodwn build via GitHub Actions.

if you want to build the website, issue the following command on R console:

```R
pkgdown::build_site()
```

Compare this output to what the website for nipnTK looks like. The nutriverse theme/template is not working and the additional features for pkgdown are not showing...

**Comment by ernestguevarra** [comment]
My suggestion is to revert the vignette and README back to Rmd until pkgdown has full Quarto support. Right now, all that we are using Quarto for that is different from Rmd are the callouts and that is not getting implemented properly by pkgdown.

I have read up on others work to make Quarto work for README and vignettes and pkgdown. It is not impossible but it will take time to configure our documentation workflow.

For me what is more important is a more maintainable package documentation that will pass CRAN and easy to maintain. I think we will be updating documentation a lot after we do a pre-release for alpha testing and I can't imagine how much trouble it will be if documentation will take so much effort to update compared to a fully functioning reliable automated system that is already in place.

**Comment by tomaszaba** [comment]
> My suggestion is to revert the vignette and README back to Rmd until pkgdown has full Quarto support. Right now, all that we are using Quarto for that is different from Rmd are the callouts and that is not getting implemented properly by pkgdown.
> 
> I have read up on others work to make Quarto work for README and vignettes and pkgdown. It is not impossible but it will take time to configure our documentation workflow.
> 
> For me what is more important is a more maintainable package documentation that will pass CRAN and easy to maintain. I think we will be updating documentation a lot after we do a pre-release for alpha testing and I can't imagine how much trouble it will be if documentation will take so much effort to update compared to a fully functioning reliable automated system that is already in place.

This hurts to know. Let me put it back. I will have to use the html syntax for the callouts as I had in the previous version of both README and vignettes.

**Review by ernestguevarra — APPROVED** [review]
@tomaszaba please merge to main

**Comment by tomaszaba** [comment]
> @tomaszaba please merge to main

@ernestguevarra thanks for approving this PR, however, the "merge pull request" remains disabled due to the failure in one of the GitHub checks. That on windows.

**Comment by ernestguevarra** [comment]
> > @tomaszaba please merge to main
> 
> @ernestguevarra thanks for approving this PR, however, the "merge pull request" remains disabled due to the failure in one of the GitHub checks. That on windows.

Oh yes. Let me have another go at that tonight. Then, when you get a chance tomorrow, take a peak here and it might be ready to merge by you by then!!!

**Comment by ernestguevarra** [comment]
@tomaszaba all checks are now passing. I made some other changes as well. If you see this tomorrow, go ahead and merge to main. And then make a new branch for your next steps.

**Pull request merged**
